# Generated by Django 2.0.2 on 2018-03-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extownerdata',
            name='city',
            field=models.CharField(blank=True, default='n/a', max_length=256),
        ),
    ]
