# Generated by Django 2.0.1 on 2018-02-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FdsnNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('start_date', models.CharField(blank=True, max_length=256)),
                ('restricted_status', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FdsnStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.DecimalField(decimal_places=6, max_digits=9)),
                ('restricted_status', models.CharField(blank=True, max_length=256)),
                ('start_date', models.CharField(blank=True, max_length=256)),
                ('creation_date', models.CharField(blank=True, max_length=256)),
                ('site_name', models.CharField(blank=True, max_length=256)),
                ('fdsnStation_fdsnNetwork', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fdsn_stations', to='book.FdsnNetwork')),
            ],
        ),
    ]
