# Generated by Django 2.0.1 on 2018-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_fdsnnetwork_fdsnstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdsnnetwork',
            name='name',
        ),
        migrations.AlterField(
            model_name='fdsnstation',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fdsnstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fdsnstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
