# Generated by Django 2.0.1 on 2018-02-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180207_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdsnstation',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10),
        ),
    ]
