version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "python3 stationbook/manage.py makemigrations && python3 stationbook/manage.py migrate && python3 stationbook/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src/
    ports:
      - "8000:8000"
    depends_on:
      - db