version: '2'
services:
  sbweb:
    restart: always
    build: ./stationbook/
    depends_on:
      - sbpostgres
    expose:
      - "8080"
    links:
      - sbpostgres:postgres
    env_file: .env
    volumes:
      - /data/stationbook/stationbook/static
    networks:
      - sb
    command: gunicorn stationbook.wsgi:application -w 2 -b :8080
    
  sbnginx:
    restart: always
    build: ./nginx/
    depends_on:
      - sbweb
    ports:
      - "8080:8080"
    volumes_from:
      - sbweb
    links:
      - sbweb:sbweb
    networks:
      - sb
    
  sbpostgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - sbpostgresql:/var/lib/postgresql/data
      - ./docker/postgresql/backups:/backup
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - sb

volumes:
  sbpostgresql:

networks:
  sb: