version: '2'
services:
  sbweb:
    restart: always
    build: ./stationbook/
    depends_on:
      - sbpostgres
      - sbredis
    expose:
      - "8080"
    links:
      - sbpostgres:postgres
      - sbredis:redis
    env_file: .env
    volumes:
      - /data/stationbook/stationbook/static
    command: gunicorn stationbook.wsgi:application -w 2 -b :8080
    
  sbnginx:
    restart: always
    build: ./nginx/
    depends_on:
      - sbweb
    ports:
      - "8080:8080"
    volumes_from:
      - sbweb
    links:
      - sbweb:sbweb
    
  sbpostgres:
    restart: always
    image: postgres:latest
    depends_on:
      - sbdata
    volumes_from:
      - sbdata
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - .env
    expose:
      - "5432"
    
  sbredis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    
  sbdata:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"