version: '2'
services:
  sbweb:
    restart: always
    build: ./stationbook/
    user: "994:1019"
    ports:
      - "8010:80"
    volumes:
      - /data/seismo/www/stationbook:/data/stationbook/media
      - ./db:/data/stationbook/db
    command: gunicorn stationbook.wsgi:application -w 2 -b :80

