FROM python:3.11

# Set up working directory
WORKDIR /data/stationbook

# Copy requirements file and install dependencies
COPY requirements.txt /data/stationbook
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the rest of the application code
COPY . /data/stationbook

# Command to run the application
CMD ["gunicorn", "stationbook.wsgi:application", "-w", "2", "-b", ":80"]
