FROM alpine

# Initialize
RUN mkdir -p /data/stationbook
WORKDIR /data/stationbook
COPY requirements.txt /data/stationbook/

# Setup
RUN apk update
RUN apk upgrade
RUN apk add --update python3 python3-dev postgresql-client postgresql-dev build-base gettext jpeg-dev zlib-dev
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# Clean
RUN apk del -r python3-dev postgresql

# Prepare
COPY . /data/stationbook/

RUN addgroup -g 1019 -S orfeus && \
    adduser -u 994 -S orfeus -G orfeus

RUN chown -R orfeus:orfeus /data
USER orfeus
